---
- hosts: default
  become: yes
  tasks:
    - name: git
      yum:
        name: git
        state: latest
    - name: vim
      yum:
        name: vim
        state: latest
    - name: midnight commander
      yum:
        name: mc
        state: latest
    - name: glances
      yum:
        name: glances
        state: latest
    - name: docker
      yum:
        name: docker
        state: latest